### PR TITLE
changed model notes to repeated for python list

### PR DESCRIPTION
**Pull request by billyfung**
tasting notes now put into db as a list

### CODE REVIEW

**Comment by jinpark** [comment]
Its just stumptown? no intelli or victrola?

**Comment by billyfung** [comment]
Just stumptown because I named the branch stumptown

**Comment by jinpark** [comment]
why not fix all of them here :D

**Comment by billyfung** [comment]
because what if one breaks and then you yell at me for doing them all in one thing?

**Comment by jinpark** [comment]
:D make sure they dont break

**Comment by billyfung** [comment]
yes senpai -.-

**Comment by jinpark** [comment]
saw one problem but not really related to this right now.lgtm

**Pull request merged**
